CREATE TABLE ADMIN_DATA (
    ADMIN_ID INT(5) PRIMARY KEY,
    USERNAME VARCHAR(50) NOT NULL,
    PASSWORD VARCHAR(50) NOT NULL
);

CREATE TABLE USER_LOGIN (
    USER_ID INT(3) PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL,
    MOBILE_NO INT(10) NOT NULL,
    EMAIL_ID VARCHAR(30) NOT NULL
);

CREATE TABLE MOVIE_INFO (
    MOVIE_ID INT(5) PRIMARY KEY,
    MOVIE_NAME ENUM('HINDI', 'ENGLISH') NOT NULL,
    DIRECTOR VARCHAR(10) NOT NULL,
    CAST VARCHAR(20) NOT NULL,
    MOVIE_LANGUAGE ENUM('HINDI', 'ENGLISH') NOT NULL,
    DESCRIPTION TEXT NOT NULL
);

CREATE TABLE THEATRE_EMPLOYEE (
    EMP_ID INT(10) PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL,
    PASSWORD VARCHAR(20) NOT NULL
);

CREATE TABLE TICKET_INFO (
    TICKET_ID INT(10) PRIMARY KEY,
    MOVIE_NAME ENUM('HINDI', 'ENGLISH') NOT NULL,
    THEATRE_NAME ENUM('2D', '3D') NOT NULL,
    SHOW_TIME INT(4) NOT NULL,
    SEAT_NUMBER INT(2) NOT NULL,
    FORMAT ENUM('2D', '3D') NOT NULL,
    LANGUAGE ENUM('HINDI', 'ENGLISH') NOT NULL
);

CREATE TABLE PAYMENT_INFO (
    PAYMENT_ID INT(10) PRIMARY KEY,
    USERNAME VARCHAR(20) NOT NULL,
    AMOUNT INT(10) NOT NULL
);

CREATE TABLE THEATRE_INFO (
    THEATRE_ID INT(5) PRIMARY KEY,
    MOVIE_ID_FK INT(5) NOT NULL,
    SHOW_TIME INT(4) NOT NULL,
    TOTAL_SEATS INT(20) NOT NULL,
    FOREIGN KEY (MOVIE_ID_FK) REFERENCES MOVIE_INFO(MOVIE_ID)
);
